### ISSUE TITLE
[BE | Spring] Member 모듈 및 인증 AOP 구현

### ISSUE THREAD

**Issue by namkikim0718** [KTB-Sixmen/gitfolio_back_spring#13]
### Description

- Member 모듈을 구현해야 합니다.

### TODO

- [x] Member 모듈 생성
- [x] RDB에 저장할 Member 엔티티 관련 구현
- [x] NoSQL에 저장할 MemberAdditionalInfo 엔티티 관련 구현
- [x] 인증이 필요한 요청을 검증하는 @AuthRequired 어노테이션을 AOP를 활용해 구현
