### ISSUE TITLE
[BE | Spring] Activity 필드 삭제

### ISSUE THREAD

**Issue by namkikim0718** [KTB-Sixmen/gitfolio_back_spring#30]
### Description

- 회원 추가정보 필드와 이력서 필드에서 Activity필드를 삭제해야합니다.
- 이력서 목록 조회 시 사용자의 프로필 사진 링크도 함께 보냅니다.

### TODO

- [x] Activity 관련 내용 삭제
- [x] 이력서 목록조회 DTO에 프로필 사진 추가
- [x] 이력서 상세조회 시 전화번호는 포함하지 않도록 수정
