### ISSUE TITLE
[BE | Spring] 결제모듈 구현

### ISSUE THREAD

**Issue by namkikim0718** [KTB-Sixmen/gitfolio_back_spring#34]
### Description

- 결제 모듈을 구현해야 합니다.
- 회원 삭제 로직을 추가해야 합니다.

### TODO

- [x] payment 모듈 구현
- [x] 카카오페이 결제 구현
- [x] member에 사용중인 플랜을 저장하도록 수정
- [x] member 탈퇴 엔드포인트 구현
