### ISSUE TITLE
[BE | Cloud] 백엔드 모듈의 클라우드 환경 작동을 위한 도커 파일 검증

### ISSUE THREAD

**Issue by ghk01214** [KTB-Sixmen/gitfolio_back_spring#47]
### TODO

- [] 각 모듈별 도커 파일 작성
- [] 도커 파일 일괄 적용을 위한 도커 컴포즈 파일 작성
- [] 클라우드 환경에서 작동 테스트
