### ISSUE TITLE
[BE | Spring] 프로필 이미지 로직 수정

### ISSUE THREAD

**Issue by namkikim0718** [KTB-Sixmen/gitfolio_back_spring#53]
### Description

- Member 모듈에서 프로필 이미지 로직을 변경해야합니다.

### TODO

- [x] 내 이력서 조회에서 최신순으로 정렬해서 createdAt이랑 updatedAt 포함해서 보내주기
- [x] 회원 기본 정보 수정 시 avatarUrl에 S3 prefix로 같이 저장하도록 수정
- [x] 이력서 직접 수정 시 프로필 이미지도 수정하는 로직 추가
