### ISSUE TITLE
[BE | Spring] 이력서 공개 여부필드 추가

### ISSUE THREAD

**Issue by namkikim0718** [KTB-Sixmen/gitfolio_back_spring#70]
### Description

- 이력서 공개 여부 필드를 추가해야 합니다.

### TODO

- [x] 이력서에 visibility 필드 추가
- [x] 전체 조회 시 visibility가 PUBLIC인 것만 조회
- [x] 이력서 공개 여부 변경하는 엔드포인트 추가 

### ETC (관련 자료 및 링크, 사진 등)
