### ISSUE TITLE
[BE | Spring] 이력서 생성 버그 해결 및 리팩토링

### ISSUE THREAD

**Issue by namkikim0718** [KTB-Sixmen/gitfolio_back_spring#79]
### Description

- 회원 가입시에 GithubName이 없는 경우에 null로 들어가면서 이력서 생성시 AI모듈에서 에러가 발생합니다.
- 단위 테스트 시 레이어드 아키텍쳐의 한계로 결합이 강하게 되어있습니다.
- NoArgsConstructor에 접근 제어가 되어있지 않아 위험합니다.

### TODO

- [x] GithubName없으면 null이 아닌 빈 문자열로 넣도록 수정
- [x] 패키지 구조 변경
- [x] 영속성 객체외 도메인 객체 분리
- [x] NoArgsConstructor의 AccessLevel을 PROTECTED로 변경
